pubnub:
  publish_key: <%= ENV['PUBNUB_PUBLISH_KEY'] || "pub-c-806ef41c-8fdb-45c9-8ddd-da053b45a04a" %>
  subscribe_key: <%= ENV['PUBNUB_SUBSCRIBE_KEY'] || "sub-c-5811c59e-bbce-11e2-846b-02ee2ddab7fe" %>

hipchat:
  api_key: <%= ENV['HIPCHAT_API_KEY'] %>
  room: <%= ENV['HIPCHAT_ROOM'] || 'Admo Dev' %>

dashboard:
  uri: <%= ENV['DASHBOARD_URI'] || 'http://localhost:3030/widgets/' %>
  api_key: <%= ENV['DASHBOARD_API_KEY'] || 'YOUR_AUTH_TOKEN' %>

general:
  hostname: <%= ENV['GENERAL_HOSTNAME'] || 'localhost' %>
  protocol: <%= ENV['GENERAL_PROTOCOL'] || 'https' %>

gmaps:
  api_key: AIzaSyAuEhwdsqjl8kjyCWrtZLkpvzOEJIulVtc

support:
  email: support@admo.co

s3:
  region:<%= ENV['S3_REGION'] %>
  bucket_name:<%= ENV['S3_BUCKET'] %>
  access_key_id:<%= ENV['S3_KEY'] %>
  secret_access_key:<%= ENV['S3_SECRET'] %>

email:
  from: <%= ENV['EMAIL_FROM'] || 'system@admo.co' %>
  user_name: <%= ENV['EMAIL_USER_NAME'] || 'system@admo.co' %>
  password: <%= ENV['EMAIL_PASSWORD'] || '' %>
  smtp_hostname: <%= ENV['EMAIL_SMTP_HOSTNAME'] || 'smtp.gmail.com' %>
  smtp_port: <%= ENV['EMAIL_SMTP_PORT'] || '587' %>
  smtp_domain: <%= ENV['EMAIL_DOMAIN'] || 'admo.co' %>

